feat: implement configreloaded event
hyprland-community/hyprland-rs pull request #215
Opened 2024-04-19 17:20 UTC by diniamo

@yavko rebase on master after you merge this please

2024-04-19 17:44 UTC, yavko commented
I'll wait for #208 to get merged first, since changing implementations to the event listener stuff

2024-04-22 19:26 UTC, diniamo commented
I already did that for my project: https://github.com/diniamo/hyprland-rs/tree/configreloaded-and-workspacerules

2024-04-22 20:10 UTC, yavko commented
> ~~I already did that for my project: https://github.com/diniamo/hyprland-rs/tree/configreloaded-and-workspacerules~~
> 
> Never mind, that was before the big merge, but I'm not gonna rebase master, I'm gonna rebase add-events once you rebase that.

Okay one sec

2024-05-03 06:29 UTC, yavko requested changes

2024-05-03 06:29 UTC, yavko commented on src/shared.rs
> +    ParseError(<i32 as FromStr>::Err),
Please instead create an error using the new Hyprland-rs error types that are more detailed, and can be used to provide more insight

2024-05-03 06:29 UTC, yavko commented on src/shared.rs
> +    ParseError(<i32 as FromStr>::Err),
also, even if you did use this, you should've used https://doc.rust-lang.org/std/num/struct.ParseIntError.html

2024-05-03 06:29 UTC, yavko commented on src/event_listener/shared.rs
> +pub struct EmptyEventData;
are you 100% sure you can't figure out how to do it without?

2024-05-03 06:30 UTC, yavko commented
also fix the merge conflicts

2024-06-04 06:19 UTC, merged