extend Version struct with version field
hyprland-community/hyprland-rs pull request #287
Opened 2024-11-05 10:22 UTC by simon-bueler

resolves #286

2024-11-05 14:15 UTC, H3rmt commented
It might be beneficial to make this struct as backwards compatible as possible.

I use this to check if the current Hyprland Instance is newer than a certain version to prevent users from getting weird serde errors.

I don't exactly know when the version field was added but this would mean hyprswitch wouldn't be able to check the version of hyprswitch lower than the version the "version" field was added to the Version output.

Then users would again get a weird serde error instead of a warning explaining that they are running version 0.41 and need at least 0.42

2024-11-05 14:22 UTC, H3rmt commented
v0.44.1 (newest from aur has no version field)

2024-11-05 14:28 UTC, H3rmt commented
added with https://github.com/hyprwm/Hyprland/commit/7564b26b7d386d248eaa47c1a481c09eefd8e3ca

2024-11-05 14:34 UTC, H3rmt commented
![image](https://github.com/user-attachments/assets/28aaa0fc-44b3-48bc-a6b9-af9675e01827)

2024-11-05 14:36 UTC, H3rmt commented
using 
```rs
#[serde(default)]
/// The Hyprland version
pub version: String,
```
returns "" as the Version string if the Hyprland version is to new

2024-11-05 14:57 UTC, yavko approved these changes

2024-11-05 14:58 UTC, yavko commented
> using 
> ```rs
> #[serde(default)]
> /// The Hyprland version
> pub version: String,
> ```
> returns "" as the Version string if the Hyprland version is to new:
> 
> ```
> TRACE Hyprland Version { branch: "", commit: "4520b30d498daca8079365bdb909a8dea38e8d55", version: "", dirty: false, commit_message: "version: bump to 0.44.1", commit_date: "Wed Oct 9 12:54:39 2024", tag: "v0.44.1", commits: "5309", build_aquamarine: "0.4.3", flags: [] }
> ```

Perhaps that's a good idea

2024-11-05 15:03 UTC, simon-bueler commented
@H3rmt: as for hyprswitch, if we create a new version of hyprland-rs (probably 0.4.0-beta.2) you can rewrite the check to fit both variants and add the new hyprland-rs to that version (probably hyprswitch 3.0.2 or so)

2024-11-05 15:06 UTC, H3rmt commented
I made the version check optional, so hyprswitch continues working if an outdated or old version is found, but it shows a warning if the Tag wasn't available.

This is needed to allow running the version check for <0.44.1 on git version without the tag

2024-11-05 15:08 UTC, H3rmt commented
But having the version field set to an empty string (if none was reported) is definitely needed as it would break getting the version even on the current aur release.

2024-11-08 04:27 UTC, yavko requested changes
I'd like it not to break fairly recent versions, so i think setting a default would be nice.

2024-11-08 14:05 UTC, simon-bueler commented
Sorry for being so incapable but I actually don't know how to add that in rust. Would you be so kind to help me there?

2024-11-08 14:08 UTC, H3rmt commented
Do you see the change request on GitHub?
It contains the rust code needed to populate the version attribute with an empty string

2024-11-08 14:10 UTC, H3rmt commented
```rs
#[serde(default)]
/// The Hyprland version
pub version: String, 
```

That's the rust code needed to add the version as an "optional" value.

2024-11-08 15:08 UTC, yavko commented
Actually, why not make it an option instead, an empty string is less meaningful.

2024-11-08 16:52 UTC, simon-bueler commented on src/data/regular.rs
> +    /// The Hyprland version
Its in the second commit

2024-11-08 21:07 UTC, yavko requested changes
Try making it into an option instead, it would make more sense that way.

2024-11-11 01:57 UTC, yavko approved these changes
thx

2024-11-11 02:05 UTC, merged

2024-11-19 19:43 UTC, H3rmt commented
@yavko they removed nearly every value from the version command (at least they return "" instead of removing the fields)

2024-11-20 02:04 UTC, yavko commented
> @yavko they removed nearly every value from the version command (at least they return "" instead of removing the fields)

Bruh, r u sure its not a bug