chore: implement a macro for CommandContent
hyprland-community/hyprland-rs pull request #46
Opened 2023-05-05 12:19 UTC by cyrinux

2023-05-05 20:28 UTC, yavko requested changes

2023-05-05 20:28 UTC, yavko commented on src/shared.rs
> +macro_rules! Command {
could you make it lowercase?

2023-05-06 06:26 UTC, cyrinux commented on src/shared.rs
> +macro_rules! Command {
yep done

2023-05-06 07:05 UTC, yavko approved these changes
LGTM

2023-05-06 07:05 UTC, merged