fixed movetoworkspace and movetoworkspacesilent
hyprland-community/hyprland-rs pull request #49
Opened 2023-05-13 18:26 UTC by levnikmyskin

Hi!
the `movetoworkspace` and `movetoworkspacesilent` were not properly working with special workspaces. This should fix it now.   
  
Please notice I didn't check if there were other broken dispatchers.

Cheers :)

2023-05-13 23:49 UTC, yavko requested changes
Looks good, just could you add support for binds? This function is also used in `config::binds::Binder::gen_str` :)

2023-05-13 23:49 UTC, yavko commented on src/dispatch.rs
> +        MoveToWorkspaceSilent(work, Some(win)) => format!("movetoworkspacesilent {work},{win}"),
Could you add `{sep}` so it also works in binds?

2023-05-13 23:49 UTC, yavko commented on src/dispatch.rs
> +        MoveToWorkspace(work, Some(win)) => format!("movetoworkspace {work},{win}"),
Could you add `{sep}` so it also works in binds?

2023-05-13 23:49 UTC, yavko commented on src/dispatch.rs
>          MoveToWorkspace(work, None) => format!("movetoworkspace {work}"),
Could you add `{sep}` so it also works in binds?

2023-05-13 23:49 UTC, yavko commented on src/dispatch.rs
>          MoveToWorkspaceSilent(work, None) => format!("movetoworkspacesilent {work}"),
Could you add `{sep}` so it also works in binds?

2023-05-14 10:11 UTC, levnikmyskin commented
Yeah sure, but I don't know how `sep` works here. From line 467:
`let sep = if dispatch { " " } else { "," };`

Does this mean `sep` would be a white space here? because if so, then this wouldn't work.

2023-05-19 09:40 UTC, levnikmyskin commented
Hey, sorry for the delay. Been pretty busy. Should be fine now, right?

2023-05-28 08:01 UTC, yavko approved these changes
lgtm

2023-05-28 08:01 UTC, merged